# Generated by Django 5.1.5 on 2025-01-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Songs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("artist", models.CharField(max_length=255)),
                ("album", models.CharField(blank=True, max_length=255, null=True)),
                ("duration", models.IntegerField()),
                ("mp3_url", models.URLField()),
                (
                    "album_art",
                    models.ImageField(blank=True, null=True, upload_to="album_art/"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
